### ISSUE TITLE
Release v2.8.0

### ISSUE THREAD

**Issue by vorburger** [macisamuele/language-formatters-pre-commit-hooks#150]
@macisamuele issue to tracking when you will release a v2.8.0 (to notify me and perhaps others to upgrade whenever you do).

I'm currently using a `rev: 54f7f7c5cb9501110b928f2a98faa8024142f8d7` in order to get #147 which is not on 2.7.0.

`pre-commit autoupdate` keeps changing that (newer) rev to the (older) `rev: v2.7.0` due to https://github.com/pre-commit/pre-commit/issues/2811.

**Comment by macisamuele** [comment]
I'll try to release the new version in the next days.

If you are using an unpublished version "just" to have access to the most recent java formatter I would advice you to use
https://github.com/macisamuele/language-formatters-pre-commit-hooks/blob/master/language_formatters_pre_commit_hooks/pretty_format_java.py#L62

instead of using an unreleased version of the pre commit hooks you could explicitly ask for a specific java formatter in the hook setup via `--google-java-formatter-version` argument

**Comment by vorburger** [comment]
@macisamuele thank you, that's very useful to know! I've raised #151 to add easy to spot documentation about this.
